-- CLIENTES
CREATE TABLE CLIENTE (
  ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
  CPF VARCHAR(11) NOT NULL,
  NOME VARCHAR(100) NOT NULL
);

-- FORMAS DE PAGAMENTO
CREATE TABLE FORMA_PAGAMENTO (
  ID_FORMA_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
  DESCRICAO VARCHAR(10)
);

-- TIPOS DE PRODUTO
CREATE TABLE TIPO_PRODUTO (
  ID_TIPO_PROD INT AUTO_INCREMENT PRIMARY KEY,
  DESCRICAO VARCHAR(50)
);

-- PRODUTOS
CREATE TABLE PRODUTO (
  ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(100),
  ID_TIPO_PROD INT,
  PRECO_UNIDADE REAL,
  FOREIGN KEY (ID_TIPO_PROD) REFERENCES TIPO_PRODUTO(ID_TIPO_PROD)
);

-- CARGOS
CREATE TABLE CARGO (
  ID_CARGO INT AUTO_INCREMENT PRIMARY KEY,
  DESCRICAO VARCHAR(10)
);

-- FUNCIONÁRIOS
CREATE TABLE FUNCIONARIO (
  ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
  CPF VARCHAR(11) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  ID_CARGO INT,
  FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO)
);

-- TURNOS
CREATE TABLE TURNO (
  ID_TURNO INT AUTO_INCREMENT PRIMARY KEY,
  DESCRICAO VARCHAR(10)
);

-- FORNADAS
CREATE TABLE FORNADA (
  ID_FORNADA INT AUTO_INCREMENT PRIMARY KEY,
  DATA_HORA DATETIME,
  ID_TURNO INT,
  ID_FUNCIONARIO INT,
  FOREIGN KEY (ID_TURNO) REFERENCES TURNO(ID_TURNO),
  FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
);

-- PRODUTO-FORNADA
CREATE TABLE PRODUTO_FORNADA (
  ID_PROD_FORN INT AUTO_INCREMENT PRIMARY KEY,
  ID_PRODUTO INT,
  ID_FORNADA INT,
  QUANTIDADE INT,
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
  FOREIGN KEY (ID_FORNADA) REFERENCES FORNADA(ID_FORNADA)
);

-- PEDIDOS
CREATE TABLE PEDIDO (
  ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
  DATA DATETIME NOT NULL,
  VALOR_TOTAL REAL NOT NULL,
  ID_CLIENTE INT,
  ID_FORMA_PAGAMENTO INT,
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO)
);

-- DEVOLUÇÕES
CREATE TABLE DEVOLUCAO (
  ID_DEVOLUCAO INT AUTO_INCREMENT PRIMARY KEY,
  MOTIVO VARCHAR(300),
  DATA_DEVOLUCAO DATETIME,
  QUANTIDADE_DEVOLVIDA INT
);

-- LISTA DE COMPRA
CREATE TABLE LISTA_COMPRA (
  ID_PEDIDO INT,
  ID_PROD_FORN INT,
  QUANTIDADE INT,
  ID_DEVOLUCAO INT NULL,
  FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
  FOREIGN KEY (ID_PROD_FORN) REFERENCES PRODUTO_FORNADA(ID_PROD_FORN),
  FOREIGN KEY (ID_DEVOLUCAO) REFERENCES DEVOLUCAO(ID_DEVOLUCAO)
);

-- CLIENTES
INSERT INTO CLIENTE (CPF, NOME) VALUES
('32165498700', 'Fernanda Ribeiro'),
('65498732100', 'Bruno Costa'),
('14725836900', 'Aline Fernandes'),
('96385274100', 'Marcelo Almeida'),
('55566677788', 'Roberta Lima'),
('77788899901', 'Carlos Silva');

-- FORMAS DE PAGAMENTO
INSERT INTO FORMA_PAGAMENTO (DESCRICAO) VALUES
('PIX'),
('Crédito'),
('Débito'),
('Boleto');

-- TIPOS DE PRODUTO
INSERT INTO TIPO_PRODUTO (DESCRICAO) VALUES
('Salgado'),
('Bebida'),
('Integral'),
('Fatia'),
('Miniatura'),
('Doces');

-- PRODUTOS
INSERT INTO PRODUTO (NOME, DESCRICAO, ID_TIPO_PROD, PRECO_UNIDADE) VALUES
('Pão Integral', 'Pão com farinha integral e sementes.', 3, 1.20),
('Croissant', 'Croissant amanteigado recheado com presunto e queijo.', 1, 5.00),
('Coxinha', 'Coxinha de frango com catupiry.', 4, 6.00),
('Enroladinho de Salsicha', 'Massa crocante recheada com salsicha.', 4, 5.50),
('Pastel de Queijo', 'Pastel frito recheado com queijo muçarela.', 4, 5.00),
('Refrigerante Lata', 'Lata de refrigerante de 350ml.', 2, 4.50),
('Suco Natural', 'Suco de frutas naturais 300ml.', 2, 6.00),
('Pão de Queijo', 'Pão de queijo tradicional.', 1, 2.00),
('Mini Sonho', 'Sonho pequeno com recheio de doce de leite.', 5, 1.50),
('Pão Doce', 'Pão doce com cobertura de coco.', 2, 2.50),
('Bolo de Chocolate', 'Bolo de chocolate com cobertura.', 2, 18.00),
('Mini Bolo de Laranja', 'Mini bolo de laranja individual.', 5, 3.50),
('Torta de Morango', 'Torta de morango com creme de baunilha.', 6, 15.00);

-- CARGOS
INSERT INTO CARGO (DESCRICAO) VALUES
('Padeiro'),
('Atendente'),
('Gerente'),
('Caixa');

-- FUNCIONÁRIOS
INSERT INTO FUNCIONARIO (CPF, NOME, ID_CARGO) VALUES
('22233344455', 'Paulo Mendes', 1),
('77788899900', 'Juliana Castro', 2),
('99900011122', 'Rafael Gomes', 2),
('88877766655', 'Luciana Dias', 1),
('33344455566', 'Maria Souza', 3),
('55544433322', 'José Rocha', 4);

-- TURNOS
INSERT INTO TURNO (DESCRICAO) VALUES
('Manhã'),
('Tarde'),
('Noite');

-- FORNADAS
INSERT INTO FORNADA (DATA_HORA, ID_TURNO, ID_FUNCIONARIO) VALUES
('2025-05-08 06:00:00', 1, 1),
('2025-05-08 14:00:00', 2, 1),
('2025-05-08 22:00:00', 3, 4);

-- PRODUTO-FORNADA
INSERT INTO PRODUTO_FORNADA (ID_PRODUTO, ID_FORNADA, QUANTIDADE) VALUES
(1, 1, 100),
(2, 2, 50),
(3, 3, 30),
(4, 1, 200),
(5, 2, 150),
(6, 3, 75);

-- PEDIDOS
INSERT INTO PEDIDO (DATA, VALOR_TOTAL, ID_CLIENTE, ID_FORMA_PAGAMENTO) VALUES
('2025-05-08 07:00:00', 5.00, 1, 1),
('2025-05-08 15:00:00', 15.00, 2, 2),
('2025-05-08 18:00:00', 8.50, 3, 3),
('2025-05-08 19:30:00', 10.00, 4, 4),
('2025-05-08 21:00:00', 7.00, 5, 1);

-- DEVOLUÇÕES (opcional, se houver)
INSERT INTO DEVOLUCAO (MOTIVO, DATA_DEVOLUCAO, QUANTIDADE_DEVOLVIDA) VALUES
('Produto queimado', '2025-05-08 16:00:00', 1),
('Produto trocado', '2025-05-08 20:00:00', 2);

-- LISTA DE COMPRA
INSERT INTO LISTA_COMPRA (ID_PEDIDO, ID_PROD_FORN, QUANTIDADE, ID_DEVOLUCAO) VALUES
(1, 1, 10, NULL),
(2, 2, 1, 1),
(3, 3, 3, NULL),
(4, 4, 2, NULL),
(5, 5, 5, 2);
